export const Event_Values = {
  event_id: 0,
  event_name: "",
  event_active: true,
  event_dates: [""],
  event_day: "",
  event_month: "",
  event_year: 0,
  event_discount: false,
  event_discount_per: 0,
  event_img: "",
  event_price: [{}],
  event_payment: [{}],
  event_publish: "",
  event_selling_data: [{}],
  event_tickets: [""],
  event_num: 1,
  event_time_sell: [{}],
};
